In [1]:
"""本文件主要是用来练习Numpy,之前没有用过，需要熟悉一下基本api（刚顺便看了一下jupyter的文件格式，原来是json，真是机智）"""

'本文件主要是用来练习Numpy,之前没有用过，需要熟悉一下基本api（刚顺便看了一下jupyter的文件格式，原来是json，真是机智）'

In [2]:
print('Hello World!')

Hello World!


In [3]:
import numpy as np

In [4]:
print(np.__version__)

1.13.1


In [5]:
"""初始化一个全0的数组,是[] 类型的"""
Z = np.zeros(10)

In [6]:
print(Z)

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


In [7]:
np.zeros_like?
"""这里有个类似的接口就是zeros_like，这个是返回一个相同结构的全0数组"""

'这里有个类似的接口就是zeros_like，这个是返回一个相同结构的全0数组'

In [8]:
Z = np.zeros_like([1,2,3])

In [9]:
print(Z)

[0 0 0]


In [10]:
"""这个和？功能类似，应该是个稍微简略的版本，缺少Call signature、Type、String form、File、Class docstring 部分 """
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

In [11]:
np.add?

In [12]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]


In [13]:
"""值域范围设定，这个函数的意思应该是初始化一个设定的递增数组，参数就是初始值和数组长度"""
Z = np.arange(10,50)
print(Z)
Z[0] = 90
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[90 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [14]:
"""看来这个函数是固定加1，不管初始值是什么类型"""
Z = np.arange(-1.3,40)
print(Z)

[ -1.3  -0.3   0.7   1.7   2.7   3.7   4.7   5.7   6.7   7.7   8.7   9.7
  10.7  11.7  12.7  13.7  14.7  15.7  16.7  17.7  18.7  19.7  20.7  21.7
  22.7  23.7  24.7  25.7  26.7  27.7  28.7  29.7  30.7  31.7  32.7  33.7
  34.7  35.7  36.7  37.7  38.7  39.7]


In [15]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


In [16]:
"""这个有个限制就是，数组个数必须正好和后面矩阵的元素数量一致，多少都会报错"""
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [17]:
np.eye?


In [18]:
"""np.eye(N, M=None, k=0, dtype=<class 'float'>) 接口说明
N：行数
M：列数，没有就是和行数相同
K：单位矩阵开始的列数，默认为0
dtype：数据类型，默认应该是float
不过为什么叫eye呢？因为单位矩阵是E吗"""
Z = np.eye(3,4,1,int)
print(Z)

[[0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [19]:
Z = np.random.random((3,3,3))
print(Z)

[[[ 0.65756052  0.37009626  0.89134038]
  [ 0.67799156  0.50145366  0.55176948]
  [ 0.58824558  0.29258496  0.27386923]]

 [[ 0.80900282  0.39320574  0.89613667]
  [ 0.00479089  0.24513566  0.92243371]
  [ 0.3957955   0.39394477  0.21314738]]

 [[ 0.73761596  0.69302119  0.5526019 ]
  [ 0.60519434  0.46682218  0.15922757]
  [ 0.49256259  0.91503503  0.89394789]]]


In [20]:
Z = np.random.random((10,10))
"""这里遇到一个插曲，min函数没有加括号，调用方法变成了函数对象赋值了，看来python中一切皆是对象，此言不虚"""
ZMin, ZMax = Z.min(),Z.max()
print("ZMin is ",ZMin)
print("ZMax is ",ZMax)

ZMin is  0.00249636942306
ZMax is  0.973455704943


In [21]:
"""按照numpy的函数定义规则，瞎写了一个average，竟然好用，和数组的mean方法是一个意思,查了一下average的源代码，
    if weights is None:
        avg = a.mean(axis)
        scl = avg.dtype.type(a.size/avg.size)
当权重没有设置的情况下，调的也是mean()方法"""
Z = np.random.random(30)
ZAverage = np.average(Z)
print(Z.mean())
print(ZAverage)

0.379883545114
0.379883545114


In [22]:
"""使用：-1 的切片方法，给边界值赋值为1，不过不仅让行的边界为1，列的边界也为1，这个还是有点意外，目前想不到这种应用场景是什么"""
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]


In [23]:
"""既然这个方法叫pad，那就是给已有数组的边缘加一圈数，看参数定义就是
这里有意思的参数就是mode这个，有很多种模式，对数组的操作我看也是尽力了"""
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)
Z = np.pad(Z, pad_width=[3,3],mode='edge')
print(Z)

[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]]
[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  1.  1.  1.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  1.  1.  1.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  1.  1.  1.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  1.  1.  1.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  1.  1.  1.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


In [24]:
"""看一下这个函数定义 np.pad(array, pad_width, mode, **kwargs)"""
np.pad?

In [25]:
"""nan就是一个对象，表示什么的没有，而且和自己都不相等，和其他语言，比如Java中的NULL 还是不一样的"""
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


In [26]:
np.diag?

In [27]:
"""这个好像比较难理解，我真是佩服numpy的能力，能提供这么多数组的操作，这些能力进行组合，能产生什么化学反应，真是想不出来。
想熟练使用这些操作，还是要从数学计算出发，针对数据处理需求，选择合适的方法，才能对代码的理解更透彻，使用更准确呀，继续撸"""
Z = np.diag(1 + np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [28]:
"""矩阵设置成棋盘？是不是中间就换成楚河汉界就行了？
结果不是，这个使用的意思是，通过步长的设定，从第2行，第1列开始，行列都跳步长为2，赋值1，然后从第1行，第2列开始，行列都跳步长为2，赋值1"""
Z = np.zeros((8,8), dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [29]:
print((6,7,8))
index100 = np.unravel_index(100,(6,7,8))
print(index100)

(6, 7, 8)
(1, 5, 4)


In [30]:
np.unravel_index?


In [31]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


In [32]:
np.tile?

In [33]:
np.array([[0,1],[1,0]])


array([[0, 1],
       [1, 0]])

In [34]:
"""这个和用上面那个用切片的还不太一样啊"""
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [35]:
"""这里要注意的就是矩阵减去一个数，是每个值都减个数，这个和矩阵的一般操作也是一样的"""
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z = (Z - Zmin)/(Zmax - Zmin)
print(Z)

[[ 0.95296562  0.79834186  0.06967837  0.36975973  0.33737686]
 [ 0.94209175  0.05085108  0.03273031  0.32087516  0.03319067]
 [ 0.04237651  0.06713271  1.          0.79461851  0.        ]
 [ 0.83957369  0.31838364  0.61110341  0.37776703  0.19075273]
 [ 0.72651262  0.93348988  0.30001765  0.4097472   0.4052408 ]]


In [42]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
print(color)
print(color[3])

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]
uint8


In [43]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]]


In [49]:
Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [52]:
"""注意np.sum的区别"""
print(range(5))
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

range(0, 5)
10
10


In [53]:
Z = np.arange(10)

In [54]:
Z**Z

array([        1,         1,         4,        27,       256,      3125,
           46656,    823543,  16777216, 387420489])

In [55]:
2 << Z >> 2

array([  0,   1,   2,   4,   8,  16,  32,  64, 128, 256])

In [56]:
Z <- Z

array([False, False, False, False, False, False, False, False, False, False], dtype=bool)

In [57]:
1j*Z

array([ 0.+0.j,  0.+1.j,  0.+2.j,  0.+3.j,  0.+4.j,  0.+5.j,  0.+6.j,
        0.+7.j,  0.+8.j,  0.+9.j])

In [58]:
Z/1/1

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [61]:
"这里的操作都是不行的吧"
2 < Z > 2

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [62]:
np.array(0) / np.array(0)


/Users/maddy/dev/Anaconda3/anaconda3/envs/pyCharm/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


nan

In [63]:
np.array(0) // np.array(0)


/Users/maddy/dev/Anaconda3/anaconda3/envs/pyCharm/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


0

In [64]:
np.array([np.nan]).astype(int).astype(float)

array([ -9.22337204e+18])

In [65]:
Z = np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(Z)), Z))

[ 10.  -8.  10.  -3.  -9.   9. -10.  -7.  -2.   1.]


In [66]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[0 1 2 3 9]


In [69]:
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0
print(Z)

[ inf]


In [70]:
_ = np.seterr(**defaults)

In [71]:
with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0

In [72]:
print(Z)

[ inf]


In [73]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

In [74]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print ("Yesterday is " + str(yesterday))
print ("Today is " + str(today))
print ("Tomorrow is "+ str(tomorrow))

Yesterday is 2019-06-22
Today is 2019-06-23
Tomorrow is 2019-06-24


In [75]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [76]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)

array([ 3.,  3.,  3.])

In [77]:
np.divide(A,2,out=A)

array([ 0.5,  0.5,  0.5])

In [78]:
np.negative(A,out=A)

array([-0.5, -0.5, -0.5])

In [79]:
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

In [80]:
Z = np.random.uniform(0,10,10)

print (Z - Z%1)

[ 1.  9.  4.  2.  5.  1.  9.  7.  8.  2.]


In [81]:
print (np.floor(Z))

[ 1.  9.  4.  2.  5.  1.  9.  7.  8.  2.]


In [82]:
print (np.ceil(Z)-1)

[ 1.  9.  4.  2.  5.  1.  9.  7.  8.  2.]


In [83]:
print (Z.astype(int))

[1 9 4 2 5 1 9 7 8 2]


In [84]:
print (np.trunc(Z))

[ 1.  9.  4.  2.  5.  1.  9.  7.  8.  2.]


In [85]:
Z = np.zeros((5,5))
Z += np.arange(5)
print (Z)

[[ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]]


In [86]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print (Z)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]


In [87]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print (Z)

[ 0.09090909  0.18181818  0.27272727  0.36363636  0.45454545  0.54545455
  0.63636364  0.72727273  0.81818182  0.90909091]


In [88]:
Z = np.random.random(10)
Z.sort()
print (Z)

[ 0.15998338  0.32254322  0.38523457  0.40194255  0.61145621  0.61596856
  0.62991984  0.80214133  0.86333092  0.88938547]


In [89]:
# Z = np.arange(10)
# np.add.reduce(Z)

In [90]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

False


In [91]:
equal = np.array_equal(A,B)
print(equal)

False


In [93]:
"""设置只读"""
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

In [94]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print (R)
print (T)

[ 0.67480545  0.08519781  0.45005881  0.35312559  1.03806921  0.16492545
  0.8794821   0.80675386  0.40234014  0.79482946]
[ 0.16724223  1.09540315  1.24671005  0.21842478  0.489744    0.94440332
  0.74735136  0.06961914  1.09921677  0.07136732]


In [95]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print (Z)

[ 0.58070203  0.84451272  0.1966475   0.0346513   0.          0.27296401
  0.2813916   0.8693494   0.26850248  0.10328904]


In [96]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[( 0.  ,  0.  ) ( 0.25,  0.  ) ( 0.5 ,  0.  ) ( 0.75,  0.  )
  ( 1.  ,  0.  )]
 [( 0.  ,  0.25) ( 0.25,  0.25) ( 0.5 ,  0.25) ( 0.75,  0.25)
  ( 1.  ,  0.25)]
 [( 0.  ,  0.5 ) ( 0.25,  0.5 ) ( 0.5 ,  0.5 ) ( 0.75,  0.5 )
  ( 1.  ,  0.5 )]
 [( 0.  ,  0.75) ( 0.25,  0.75) ( 0.5 ,  0.75) ( 0.75,  0.75)
  ( 1.  ,  0.75)]
 [( 0.  ,  1.  ) ( 0.25,  1.  ) ( 0.5 ,  1.  ) ( 0.75,  1.  )
  ( 1.  ,  1.  )]]


In [97]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.16363712


In [98]:
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-3.40282e+38
3.40282e+38
1.19209e-07
-1.79769313486e+308
1.79769313486e+308
2.22044604925e-16


In [99]:
np.set_printoptions(threshold=np.nan)
Z = np.zeros((16,16))
print (Z)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 

In [100]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print (Z[index])

38


In [101]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print (Z)

[(( 0.,  0.), ( 0.,  0.,  0.)) (( 0.,  0.), ( 0.,  0.,  0.))
 (( 0.,  0.), ( 0.,  0.,  0.)) (( 0.,  0.), ( 0.,  0.,  0.))
 (( 0.,  0.), ( 0.,  0.,  0.)) (( 0.,  0.), ( 0.,  0.,  0.))
 (( 0.,  0.), ( 0.,  0.,  0.)) (( 0.,  0.), ( 0.,  0.,  0.))
 (( 0.,  0.), ( 0.,  0.,  0.)) (( 0.,  0.), ( 0.,  0.,  0.))]


In [102]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print (D)

[[ 0.          0.10569459  0.80757717  0.42982014  0.42680945  0.71328154
   0.09592061  0.60766047  0.57895349  0.68582889]
 [ 0.10569459  0.          0.90833268  0.39916568  0.39063473  0.81264062
   0.09654053  0.67660881  0.63500575  0.70553866]
 [ 0.80757717  0.90833268  0.          0.94770319  0.96550282  0.10063854
   0.88486552  0.45870128  0.55719262  0.80763939]
 [ 0.42982014  0.39916568  0.94770319  0.          0.02337608  0.84807744
   0.48900925  0.5468291   0.45789747  0.38138501]
 [ 0.42680945  0.39063473  0.96550282  0.02337608  0.          0.86565084
   0.48214434  0.56841296  0.48023112  0.40386808]
 [ 0.71328154  0.81264062  0.10063854  0.84807744  0.86565084  0.
   0.79321453  0.37396724  0.469404    0.72332292]
 [ 0.09592061  0.09654053  0.88486552  0.48900925  0.48214434  0.79321453
   0.          0.70337811  0.67451724  0.77279608]
 [ 0.60766047  0.67660881  0.45870128  0.5468291   0.56841296  0.37396724
   0.70337811  0.          0.10084211  0.34958528]
 [ 0.578

In [103]:
import scipy
import scipy.spatial
D = scipy.spatial.distance.cdist(Z,Z)
print (D)

[[ 0.          0.10569459  0.80757717  0.42982014  0.42680945  0.71328154
   0.09592061  0.60766047  0.57895349  0.68582889]
 [ 0.10569459  0.          0.90833268  0.39916568  0.39063473  0.81264062
   0.09654053  0.67660881  0.63500575  0.70553866]
 [ 0.80757717  0.90833268  0.          0.94770319  0.96550282  0.10063854
   0.88486552  0.45870128  0.55719262  0.80763939]
 [ 0.42982014  0.39916568  0.94770319  0.          0.02337608  0.84807744
   0.48900925  0.5468291   0.45789747  0.38138501]
 [ 0.42680945  0.39063473  0.96550282  0.02337608  0.          0.86565084
   0.48214434  0.56841296  0.48023112  0.40386808]
 [ 0.71328154  0.81264062  0.10063854  0.84807744  0.86565084  0.
   0.79321453  0.37396724  0.469404    0.72332292]
 [ 0.09592061  0.09654053  0.88486552  0.48900925  0.48214434  0.79321453
   0.          0.70337811  0.67451724  0.77279608]
 [ 0.60766047  0.67660881  0.45870128  0.5468291   0.56841296  0.37396724
   0.70337811  0.          0.10084211  0.34958528]
 [ 0.578

In [104]:
Z = np.arange(10, dtype=np.int32)
Z = Z.astype(np.float32, copy=False)
print (Z)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]


In [105]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print (index, value)
for index in np.ndindex(Z.shape):
    print (index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [106]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print (G)

[[ 0.36787944  0.44822088  0.51979489  0.57375342  0.60279818  0.60279818
   0.57375342  0.51979489  0.44822088  0.36787944]
 [ 0.44822088  0.54610814  0.63331324  0.69905581  0.73444367  0.73444367
   0.69905581  0.63331324  0.54610814  0.44822088]
 [ 0.51979489  0.63331324  0.73444367  0.81068432  0.85172308  0.85172308
   0.81068432  0.73444367  0.63331324  0.51979489]
 [ 0.57375342  0.69905581  0.81068432  0.89483932  0.9401382   0.9401382
   0.89483932  0.81068432  0.69905581  0.57375342]
 [ 0.60279818  0.73444367  0.85172308  0.9401382   0.98773022  0.98773022
   0.9401382   0.85172308  0.73444367  0.60279818]
 [ 0.60279818  0.73444367  0.85172308  0.9401382   0.98773022  0.98773022
   0.9401382   0.85172308  0.73444367  0.60279818]
 [ 0.57375342  0.69905581  0.81068432  0.89483932  0.9401382   0.9401382
   0.89483932  0.81068432  0.69905581  0.57375342]
 [ 0.51979489  0.63331324  0.73444367  0.81068432  0.85172308  0.85172308
   0.81068432  0.73444367  0.63331324  0.51979489]
 [

In [107]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print (Z)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


In [108]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[ 0.0338463  -0.09413385  0.05387932 -0.2567225   0.17602581  0.40645159
  -0.10664205  0.13210737 -0.12943482 -0.21537718]
 [-0.02850262 -0.1397142  -0.15337399  0.29074704  0.19602537 -0.16331037
  -0.2938981  -0.04910296 -0.06943422  0.41056405]
 [-0.62859275  0.2538848   0.24361028  0.21706056  0.04704093 -0.53829064
   0.1957775   0.02195005  0.20782609 -0.02026683]
 [ 0.16515453 -0.12468954 -0.21739117 -0.15262023 -0.12089374  0.735996
  -0.12657062 -0.10748035  0.0706085  -0.12211338]
 [ 0.35371338 -0.16044813  0.37562293 -0.51696917  0.37739302  0.09189509
  -0.38898642 -0.09213455  0.03331072 -0.07339686]]


In [109]:
Y = X - X.mean(axis=1).reshape(-1, 1)
print (Y)

[[ 0.0338463  -0.09413385  0.05387932 -0.2567225   0.17602581  0.40645159
  -0.10664205  0.13210737 -0.12943482 -0.21537718]
 [-0.02850262 -0.1397142  -0.15337399  0.29074704  0.19602537 -0.16331037
  -0.2938981  -0.04910296 -0.06943422  0.41056405]
 [-0.62859275  0.2538848   0.24361028  0.21706056  0.04704093 -0.53829064
   0.1957775   0.02195005  0.20782609 -0.02026683]
 [ 0.16515453 -0.12468954 -0.21739117 -0.15262023 -0.12089374  0.735996
  -0.12657062 -0.10748035  0.0706085  -0.12211338]
 [ 0.35371338 -0.16044813  0.37562293 -0.51696917  0.37739302  0.09189509
  -0.38898642 -0.09213455  0.03331072 -0.07339686]]


In [110]:
Z = np.random.randint(0,3,(3,10))
print ((~Z.any(axis=0)).any())

True


In [111]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print (m)

0.303078556104


In [112]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: 
    z[...] = x + y
print (it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [113]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


In [114]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[ 4.  3.  5.  2.  2.  2.  2.  3.  4.  3.]


In [116]:
"""注意和上面方法的区别"""
np.add.at(Z, I, 1)
print(Z)

[ 10.   7.  13.   4.   4.   4.   4.   7.  10.   7.]


In [117]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print (F)

[ 0.  7.  0.  6.  5.  0.  0.  0.  0.  3.]


In [118]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print (n)

8


In [119]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.sum(axis=(-2,-1))
print (sum)

[[56 50 55 45]
 [49 68 43 56]
 [44 68 49 59]]


In [120]:
"""是不是一般方法2都看着更高级些 ，因为封装过了"""
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print (sum)

[[56 50 55 45]
 [49 68 43 56]
 [44 68 49 59]]


In [121]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print (D_means)

[ 0.53474486  0.49444896  0.46062827  0.46663912  0.67590003  0.51198352
  0.54416927  0.43902547  0.58404567  0.54748512]


In [123]:
import p as pd
print(pd.Series(D).groupby(S).mean())

ModuleNotFoundError: No module named 'pandas'

In [124]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
np.diag(np.dot(A, B))

array([ 0.67215804,  0.85605964,  0.41706743,  0.78003337,  1.09129874])

In [125]:
np.sum(A * B.T, axis=1)

array([ 0.67215804,  0.85605964,  0.41706743,  0.78003337,  1.09129874])

In [126]:
np.einsum("ij,ji->i", A, B)

array([ 0.67215804,  0.85605964,  0.41706743,  0.78003337,  1.09129874])

In [127]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print (Z0)

[ 1.  0.  0.  0.  2.  0.  0.  0.  3.  0.  0.  0.  4.  0.  0.  0.  5.]


In [128]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print (A * B[:,:,None])

[[[ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]]

 [[ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]]

 [[ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]]

 [[ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]]

 [[ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]]]


In [129]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print (A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [130]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print (G)

[( 0, 40) ( 0, 98) ( 5, 29) ( 5, 43) (10, 55) (10, 56) (22, 47) (22, 57)
 (23, 42) (23, 84) (26, 60) (26, 67) (29, 43) (30, 35) (30, 53) (33, 68)
 (33, 93) (35, 53) (40, 98) (42, 84) (43, 75) (43, 89) (47, 57) (55, 56)
 (60, 67) (68, 93) (70, 70) (70, 88) (75, 89)]


In [131]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print (A)

[1 1 2 3 4 4 6]


In [132]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)

print(moving_average(Z, n=3))

[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.  14.  15.
  16.  17.  18.]


In [133]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)

print (Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [134]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

array([1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 0])

In [135]:
Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([ 0.28000075, -0.82844432, -0.12069046,  0.38816451, -0.79157674,
        0.6521477 ,  0.06744088, -0.34758338,  0.84204101,  0.02159191,
       -0.25871083,  0.75377268, -0.46694853,  0.86588533, -0.77810412,
       -0.90367228, -0.13233501, -0.44793509,  0.01968674,  0.86691918,
       -0.20150912,  0.57198776, -0.43815896,  0.99060307, -0.31820334,
       -0.90052081, -0.65792139,  0.14202923,  0.35357425, -0.80371635,
        0.23987264, -0.08542343, -0.92278028, -0.5481661 , -0.1576795 ,
       -0.41407419, -0.49714907,  0.02826148,  0.41356998, -0.75089722,
       -0.91883294,  0.31164856, -0.55664244,  0.39745138,  0.3596924 ,
       -0.40625133, -0.07841407,  0.2163117 ,  0.91732467, -0.76148561,
        0.76217163,  0.75062157, -0.86799748, -0.03190569,  0.14592952,
       -0.33213906,  0.895569  , -0.08626346,  0.07464454, -0.1738622 ,
        0.06500248,  0.00946458,  0.83322888, -0.49234726, -0.54541372,
       -0.06233875,  0.46457358,  0.70362707,  0.05151211,  0.80

In [136]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))

print (distance(P0, P1, p))

[  1.86394951   8.95886082  10.77942083   3.14985695   5.32495913
  10.7820546    7.20910869   8.79481291   6.23322929   9.14983388]


In [137]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print (np.array([distance(P0,P1,p_i) for p_i in p]))

[[  6.78177827   4.88497847  12.48987764   8.16328708   6.29378809
    8.1926494    1.06845573   2.7376181    7.66852153   2.97679405]
 [  0.90362027   2.41247167   0.66328148   6.81915267   5.07592947
    3.46326296   5.64736455   2.08484274   1.43415903   0.55459766]
 [  8.46147012   6.54326569   2.89855635   1.83251182  11.84344897
    9.57991065  14.95492352   6.34323602   6.03568193   7.65115089]
 [  6.76548349   5.46896154  10.65740989   8.92631729   4.92587583
    6.69358274   0.84412856   3.6059607    5.93944118   1.67975181]
 [  2.73735288   5.03470323  11.35692006   1.6904703    1.26207677
    4.00269671  10.85671133   7.03178651  14.71172666  11.97352533]
 [  8.65387066   6.85705219  12.64809736  10.12870987   7.23538985
    8.96402663   0.86507159   4.69016267   6.22191991   1.16112721]
 [  0.98900676   1.50281338  12.87039028   1.7110239    4.02631497
    6.51492335   7.16591548   3.72478482  12.97230548   9.21880062]
 [  5.89798274   8.09075441  10.2570997    4.65389629  

In [138]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

In [139]:
R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)



In [140]:
R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()


In [141]:

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print (Z)
print (R)

[[8 5 9 6 4 5 7 5 9 3]
 [0 0 8 3 6 2 0 9 8 2]
 [4 9 0 1 6 3 1 8 1 7]
 [0 4 2 0 3 8 4 6 8 4]
 [1 3 5 9 5 1 9 8 8 5]
 [1 4 4 8 0 0 8 9 6 4]
 [5 9 0 3 4 9 5 7 7 9]
 [7 6 8 0 2 6 9 3 3 3]
 [7 6 9 2 0 4 4 7 2 2]
 [2 4 7 0 1 9 3 1 1 3]]
[[0 0 0 0 0]
 [0 8 5 9 6]
 [0 0 0 8 3]
 [0 4 9 0 1]
 [0 0 4 2 0]]


In [142]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print (R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


In [143]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z)

rank = np.sum(S > 1e-10)
print (rank)

10


In [145]:
Z = np.random.randint(0,10,50)
print (np.bincount(Z).argmax())

5


In [146]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print (C)

[[[[4 4 3]
   [2 2 1]
   [2 2 0]]

  [[4 3 0]
   [2 1 2]
   [2 0 1]]

  [[3 0 1]
   [1 2 1]
   [0 1 1]]

  [[0 1 2]
   [2 1 0]
   [1 1 1]]

  [[1 2 2]
   [1 0 0]
   [1 1 3]]

  [[2 2 0]
   [0 0 1]
   [1 3 4]]

  [[2 0 2]
   [0 1 1]
   [3 4 3]]

  [[0 2 0]
   [1 1 3]
   [4 3 0]]]


 [[[2 2 1]
   [2 2 0]
   [2 3 2]]

  [[2 1 2]
   [2 0 1]
   [3 2 0]]

  [[1 2 1]
   [0 1 1]
   [2 0 3]]

  [[2 1 0]
   [1 1 1]
   [0 3 4]]

  [[1 0 0]
   [1 1 3]
   [3 4 4]]

  [[0 0 1]
   [1 3 4]
   [4 4 1]]

  [[0 1 1]
   [3 4 3]
   [4 1 0]]

  [[1 1 3]
   [4 3 0]
   [1 0 2]]]


 [[[2 2 0]
   [2 3 2]
   [0 3 3]]

  [[2 0 1]
   [3 2 0]
   [3 3 2]]

  [[0 1 1]
   [2 0 3]
   [3 2 0]]

  [[1 1 1]
   [0 3 4]
   [2 0 1]]

  [[1 1 3]
   [3 4 4]
   [0 1 3]]

  [[1 3 4]
   [4 4 1]
   [1 3 2]]

  [[3 4 3]
   [4 1 0]
   [3 2 3]]

  [[4 3 0]
   [1 0 2]
   [2 3 4]]]


 [[[2 3 2]
   [0 3 3]
   [4 4 4]]

  [[3 2 0]
   [3 3 2]
   [4 4 3]]

  [[2 0 3]
   [3 2 0]
   [4 3 3]]

  [[0 3 4]
   [2 0 1]
   [3 3 3]]

  [[3 4 4]
   

In [147]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print (S)

[[ 6 15  9  7 13]
 [15  0  9 10  5]
 [ 9  9  6 42  9]
 [ 7 10 42  8 13]
 [13  5  9 13  6]]


In [148]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print (S)

[[ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]]


In [150]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print (S)

[[ 16.  16.  16.  16.]
 [ 16.  16.  16.  16.]
 [ 16.  16.  16.  16.]
 [ 16.  16.  16.  16.]]


In [152]:
def iterate(Z):
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print (Z)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 1 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 0 0 0 0 0 0

In [153]:
print (Z[np.argpartition(-Z,n)[:n]])

[[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 0 1 1 1 0 0 0 0
   0 0 0 0 1 1 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0
   0 0 0 0 0 0 0 0 0 0 0 0 0 0]
  [0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 1
   1 0 0 0 0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 0 1 1
   0 0 0 0 0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0
   0 0 0 0 0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0
   0 0 0 0 0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 0
   0 0 1 0 0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 1 0 0 1 0 0 0 0 0 0
   0 1 0 1 1 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 1 0 0 0 0 0
   0 1 0 0 1 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 

In [154]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


In [155]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T, 
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print (R)

[(b'Hello',  2.5, 3) (b'World',  3.6, 2)]


In [158]:
x = np.random.rand()
np.power(x,3)
print(x*x*x)

0.3640981440048229


In [159]:
np.einsum('i,i,i->i',x,x,x)

ValueError: einstein sum subscripts string contains too many subscripts for operand 0

In [160]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print (rows)

[3]


In [169]:
"""我在这里执行报错，不知道是为什么呢，因为看不懂注释，等讨论是问下"""
Z = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
U = Z[Z.max(axis=1) != Z.min(axis=1):]
print (U)
Z = np.random.randint(0,5,(10,3))
print (Z)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print (U)

AxisError: axis 1 is out of bounds for array of dimension 1

AxisError: axis 1 is out of bounds for array of dimension 1

In [170]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print (uZ)

[[0 0 0]
 [0 0 1]
 [0 1 0]
 [0 1 1]]


In [171]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)
print ('sum')
print (np.einsum('i->', A

sum
4.89305313597


In [172]:
print ('A * B')
print (np.einsum('i,i->i', A, B)) 

A * B
[ 0.01859532  0.47342775  0.57345039  0.2554081   0.27299426  0.24094728
  0.15226055  0.31367866  0.20650932  0.05706214]


In [174]:
print (np.einsum('i,i', A, B))  

2.56433376855


In [175]:
print (np.einsum('i,j->ij', A, B))

[[ 0.01859532  0.03153194  0.02488778  0.01346217  0.02428145  0.02277078
   0.01491466  0.0182299   0.02477144  0.01399311]
 [ 0.27919437  0.47342775  0.37367081  0.20212413  0.36456718  0.3418857
   0.22393206  0.27370778  0.37192407  0.21009575]
 [ 0.42846301  0.72654144  0.57345039  0.3101879   0.55947959  0.52467167
   0.34365524  0.42004307  0.57076978  0.32242146]
 [ 0.35279559  0.59823277  0.4721779   0.2554081   0.46067438  0.43201361
   0.28296504  0.34586262  0.4699707   0.26548119]
 [ 0.20906561  0.35451095  0.27981122  0.15135408  0.27299426  0.25600997
   0.16768424  0.20495716  0.27850323  0.15732336]
 [ 0.19676495  0.33365282  0.26334814  0.14244895  0.25693227  0.24094728
   0.15781831  0.19289823  0.26211712  0.14806703]
 [ 0.18983565  0.32190286  0.25407404  0.13743245  0.24788411  0.23246205
   0.15226055  0.18610509  0.25288636  0.14285268]
 [ 0.31996648  0.54256471  0.42823977  0.23164131  0.4178067   0.39181293
   0.25663395  0.31367866  0.42623795  0.24077705]
 

In [177]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                
r_int = np.linspace(0, r.max(), 200) 
x_int = np.interp(r_int, r, x)       
y_int = np.interp(r_int, r, y)

In [178]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print (X[M])

[[ 2.  0.  1.  1.]]


In [118]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print (n)

8


In [ ]:
X = np.random.randn(100) 
N = 1000 
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print (confint)

In [1]:
print("task end")

task end
