# 第8章 数据规整 数据聚合、合并、重塑 

数据分散之后需要进行整合，并需要进行处理，但不是简单和聚合，需要进行合并处理，重塑，这一章就来看看有哪些处理函数可以使用

In [1]:
import numpy as np
import pandas as pd

In [3]:
data = pd.Series(np.random.randn(9),index =[['a','a','a','b','b','c','c','d','d'],[1,2,3,1,3,1,2,2,3]])

In [4]:
data


a  1    0.258568
   2    0.493085
   3    0.982820
b  1    0.220904
   3   -0.234071
c  1   -1.621600
   2   -1.112293
d  2    1.538021
   3    0.877319
dtype: float64

In [6]:
data.index

MultiIndex(levels=[['a', 'b', 'c', 'd'], [1, 2, 3]],
           labels=[[0, 0, 0, 1, 1, 2, 2, 3, 3], [0, 1, 2, 0, 2, 0, 1, 1, 2]])

In [7]:
data['b']

1    0.220904
3   -0.234071
dtype: float64

In [8]:
data['b':'c']

b  1    0.220904
   3   -0.234071
c  1   -1.621600
   2   -1.112293
dtype: float64

In [9]:
data.loc['b':'d']

b  1    0.220904
   3   -0.234071
c  1   -1.621600
   2   -1.112293
d  2    1.538021
   3    0.877319
dtype: float64

In [11]:
data.loc[:,2]

a    0.493085
c   -1.112293
d    1.538021
dtype: float64

In [12]:
data.unstack()

1         2         3
a  0.258568  0.493085  0.982820
b  0.220904       NaN -0.234071
c -1.621600 -1.112293       NaN
d       NaN  1.538021  0.877319

In [13]:
data.unstack().stack()

a  1    0.258568
   2    0.493085
   3    0.982820
b  1    0.220904
   3   -0.234071
c  1   -1.621600
   2   -1.112293
d  2    1.538021
   3    0.877319
dtype: float64

In [15]:
frame = pd.DataFrame(np.arange(12).reshape((4,3)), index=[['a','a','b','b'],[1,2,1,2]],columns=[['O','O','C'],['G','R','G']])

In [16]:
frame

O       C
     G   R   G
a 1  0   1   2
  2  3   4   5
b 1  6   7   8
  2  9  10  11

In [17]:
frame.index.name = ['key1','key2']

In [18]:
frame.columns.names = ['state','color']

In [19]:
frame


state  O       C
color  G   R   G
a 1    0   1   2
  2    3   4   5
b 1    6   7   8
  2    9  10  11

In [20]:
frame['O']

color  G   R
a 1    0   1
  2    3   4
b 1    6   7
  2    9  10

In [28]:
frame.swaplevel(1,0 ,axis=1)


color  G   R   G
state  O   O   C
a 1    0   1   2
  2    3   4   5
b 1    6   7   8
  2    9  10  11

In [29]:
frame.sort_index(level=1)

state  O       C
color  G   R   G
a 1    0   1   2
b 1    6   7   8
a 2    3   4   5
b 2    9  10  11

In [30]:
frame.sortlevel(0,1).sort_index(level=0)

/Users/maddy/dev/Anaconda3/anaconda3/envs/pyCharm/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: sortlevel is deprecated, use sort_index(level= ...)
  """Entry point for launching an IPython kernel.


state   C  O    
color   G  G   R
a 1     2  0   1
  2     5  3   4
b 1     8  6   7
  2    11  9  10

In [39]:
frame.sum(level=1)

state   O       C
color   G   R   G
1       6   8  10
2      12  14  16

In [41]:
frame.sum(level=1,axis=1)

color   G   R
a 1     2   1
  2     8   4
b 1    14   7
  2    20  10

In [45]:
frame = pd.DataFrame({'a':range(7),'b':range(7,0,-1),'c':['one','one','one','two','two','two','two'],'d':[0,1,2,0,1,2,3]})

In [46]:
frame

a  b    c  d
0  0  7  one  0
1  1  6  one  1
2  2  5  one  2
3  3  4  two  0
4  4  3  two  1
5  5  2  two  2
6  6  1  two  3

In [52]:
frame2 = frame.set_index(['c','d'])

In [53]:
frame2

a  b
c   d      
one 0  0  7
    1  1  6
    2  2  5
two 0  3  4
    1  4  3
    2  5  2
    3  6  1

In [49]:
frame2 = frame.set_index(['c','d'],drop=False)

In [54]:
frame2

a  b
c   d      
one 0  0  7
    1  1  6
    2  2  5
two 0  3  4
    1  4  3
    2  5  2
    3  6  1

In [55]:
frame2.reset_index()

c  d  a  b
0  one  0  0  7
1  one  1  1  6
2  one  2  2  5
3  two  0  3  4
4  two  1  4  3
5  two  2  5  2
6  two  3  6  1

In [56]:
df1 = pd.DataFrame({'key':['b','b','a','c','a','a','b'],'data1':range(7)})

In [57]:
df2 = pd.DataFrame({'key':['a','b','c'],'data2':range(3)})

In [58]:
df1

data1 key
0      0   b
1      1   b
2      2   a
3      3   c
4      4   a
5      5   a
6      6   b

In [59]:
df2

data2 key
0      0   a
1      1   b
2      2   c

In [60]:
pd.merge(df1,df2)

data1 key  data2
0      0   b      1
1      1   b      1
2      6   b      1
3      2   a      0
4      4   a      0
5      5   a      0
6      3   c      2

In [61]:
pd.merge(df1,df2,on='key')

data1 key  data2
0      0   b      1
1      1   b      1
2      6   b      1
3      2   a      0
4      4   a      0
5      5   a      0
6      3   c      2

In [62]:
df3 = pd.DataFrame({'key':['b','b','a','c','a','a','b'],'data1':range(7)})

In [63]:
df4 = pd.DataFrame({'key':['a','b','c'],'data2':range(3)})

In [64]:
pd.merge(df3,df4,left_on='key',right_on='key')

data1 key  data2
0      0   b      1
1      1   b      1
2      6   b      1
3      2   a      0
4      4   a      0
5      5   a      0
6      3   c      2

In [65]:
pd.merge(df1,df2,how='outer')

data1 key  data2
0      0   b      1
1      1   b      1
2      6   b      1
3      2   a      0
4      4   a      0
5      5   a      0
6      3   c      2

In [66]:
pd.merge(df1,df2,on='key',how='left')

data1 key  data2
0      0   b      1
1      1   b      1
2      2   a      0
3      3   c      2
4      4   a      0
5      5   a      0
6      6   b      1

In [67]:
pd.merge(df1,df2,on='key',how='inner')

data1 key  data2
0      0   b      1
1      1   b      1
2      6   b      1
3      2   a      0
4      4   a      0
5      5   a      0
6      3   c      2

In [68]:
pd.merge(df1,df2,on=['key','key'],how='outer')

data1 key  data2
0      0   b      1
1      1   b      1
2      6   b      1
3      2   a      0
4      4   a      0
5      5   a      0
6      3   c      2

In [69]:
left1 = pd.DataFrame({'key':['a','b','a','a','b','c'],'value':range(6)})

In [82]:
right1 = pd.DataFrame({'group_val':[3.5,7]},index=['a','b'])

In [71]:
left1

key  value
0   a      0
1   b      1
2   a      2
3   a      3
4   b      4
5   c      5

In [72]:
right1

group_val
a        3.5
b        7.0

In [73]:
pd.merge(left1,right1,left_on='key',right_index=True)

key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0

In [74]:
pd.merge(left1,right1,left_on='key',right_index=True,how='outer')

key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0
5   c      5        NaN

In [75]:
left = pd.DataFrame({'key1':['foo','foo','bar'],'key2':['one','two','one',]})

In [77]:
right = pd.DataFrame({'key1':['foo','foo','bar','bar'],'key2':['one','one','one','two'],'rval':[4,5,6,7]})

In [78]:
left

key1 key2
0  foo  one
1  foo  two
2  bar  one

In [79]:
right

key1 key2  rval
0  foo  one     4
1  foo  one     5
2  bar  one     6
3  bar  two     7

In [81]:
pd.merge(left,right,on='key1')

key1 key2_x key2_y  rval
0  foo    one    one     4
1  foo    one    one     5
2  foo    two    one     4
3  foo    two    one     5
4  bar    one    one     6
5  bar    one    two     7

In [83]:
left1 = pd.DataFrame({'key':['a','b','a','a','b','c'],'value':range(6)})

In [84]:
right1 = pd.DataFrame({'group_val':[3.5,7]},index=['a','b'])

In [85]:
left1

key  value
0   a      0
1   b      1
2   a      2
3   a      3
4   b      4
5   c      5

In [86]:
right1

group_val
a        3.5
b        7.0

In [87]:
pd.merge(left1,right1,left_on='key',right_index=True)

key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0

In [88]:
left2 = pd.DataFrame([[1.,2.],[3.,4.],[5.,6.]],index=['a','c','e'],columns=['M','A'])

In [89]:
left2

M    A
a  1.0  2.0
c  3.0  4.0
e  5.0  6.0

In [90]:
right2 = pd.DataFrame([[7.,8.],[9.,10.],[11.,12.],[13.,14.]],index=['b','c','d','e'],columns=['O','N'])

In [91]:
right2

O     N
b   7.0   8.0
c   9.0  10.0
d  11.0  12.0
e  13.0  14.0

In [92]:
pd.merge(left2, right2,how='outer', left_index=True,right_index=True)

M    A     O     N
a  1.0  2.0   NaN   NaN
b  NaN  NaN   7.0   8.0
c  3.0  4.0   9.0  10.0
d  NaN  NaN  11.0  12.0
e  5.0  6.0  13.0  14.0

In [93]:
left2.join(right2,how='outer')

M    A     O     N
a  1.0  2.0   NaN   NaN
b  NaN  NaN   7.0   8.0
c  3.0  4.0   9.0  10.0
d  NaN  NaN  11.0  12.0
e  5.0  6.0  13.0  14.0

In [95]:
left1.join(right1,on='key')

key  value  group_val
0   a      0        3.5
1   b      1        7.0
2   a      2        3.5
3   a      3        3.5
4   b      4        7.0
5   c      5        NaN

In [96]:
arr = np.arange(12).reshape((3,4))

In [97]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [98]:
np.concatenate([arr,arr],axis=1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [99]:
np.concatenate([arr,arr],axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [102]:
s1 = pd.Series([0,1],index=['a','b'])

In [103]:
s2 = pd.Series([2,3,4],index=['c','d','e'])

In [104]:
s3 = pd.Series([5,6],index=['f','g'])

In [105]:
pd.concat([s1,s2,s3])

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64

In [106]:
pd.concat([s1,s2,s3],axis=1)

0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0

In [107]:
s4 = pd.concat([s1,s3])

In [108]:
s2

c    2
d    3
e    4
dtype: int64

In [109]:
s4

a    0
b    1
f    5
g    6
dtype: int64

In [110]:
pd.concat([s1,s4],axis=1)

0  1
a  0.0  0
b  1.0  1
f  NaN  5
g  NaN  6

In [111]:
pd.concat([s1,s4],axis=1,join='inner')

0  1
a  0  0
b  1  1

In [113]:
pd.concat([s1,s4],axis=1,join_axes=[['a','b','c','d','e']])

0    1
a  0.0  0.0
b  1.0  1.0
c  NaN  NaN
d  NaN  NaN
e  NaN  NaN

In [114]:
result = pd.concat([s1,s3],keys=['one','two','three'])

In [115]:
result

one  a    0
     b    1
two  f    5
     g    6
dtype: int64

In [116]:
pd.concat([s1,s2,s3],axis=1,keys=['one','two','three'])

one  two  three
a  0.0  NaN    NaN
b  1.0  NaN    NaN
c  NaN  2.0    NaN
d  NaN  3.0    NaN
e  NaN  4.0    NaN
f  NaN  NaN    5.0
g  NaN  NaN    6.0

In [117]:
a = pd.Series([np.nan,2.5,np.nan,3.5,4.5,np.nan],index=['f','e','d','c','b','a'])

In [118]:
b = pd.Series(np.arange(len(a),dtype=np.float64),index=['f','e','d','c','b','a'])

In [119]:
a

f    NaN
e    2.5
d    NaN
c    3.5
b    4.5
a    NaN
dtype: float64

In [120]:
b

f    0.0
e    1.0
d    2.0
c    3.0
b    4.0
a    5.0
dtype: float64

In [121]:
b[-1] = np.nan

In [122]:
b

f    0.0
e    1.0
d    2.0
c    3.0
b    4.0
a    NaN
dtype: float64

In [123]:
np.where(pd.isnull(a),b,a)

array([ 0. ,  2.5,  2. ,  3.5,  4.5,  nan])

In [124]:
b[:-2].combine_first(a[2:])

a    NaN
b    4.5
c    3.0
d    2.0
e    1.0
f    0.0
dtype: float64

In [125]:
df1 = pd.DataFrame({'a':[1.,np.nan,5.,np.nan],'b':[np.nan,2.,np.nan,6.],'c':range(2,18,4)})

In [126]:
df2 = pd.DataFrame({'a':[5.,4.,np.nan,3.,7.],'b':[np.nan,3.,4.,6.,8.]})

In [127]:
df1

a    b   c
0  1.0  NaN   2
1  NaN  2.0   6
2  5.0  NaN  10
3  NaN  6.0  14

In [128]:
df2

a    b
0  5.0  NaN
1  4.0  3.0
2  NaN  4.0
3  3.0  6.0
4  7.0  8.0

In [129]:
df1.combine_first(df2)

a    b     c
0  1.0  NaN   2.0
1  4.0  2.0   6.0
2  5.0  4.0  10.0
3  3.0  6.0  14.0
4  7.0  8.0   NaN